//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class markers
    {
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public Nullable<double> latitudine { get; set; }
        public Nullable<double> longitudine { get; set; }
        public string ZIP { get; set; }
        public string informatii { get; set; }
        public string site { get; set; }
        public string email { get; set; }
    }
}
